class EndPoints {
  EndPoints._();
  static const String version = "/milkride/v4";
  // static const String v3 = "/milkride/v3";
  static const String prodView = "/product-view";
  static const String signup = "/signup";
  static const String signin = "/signin";
  static const String register = "/store";
  static const String otpCheck = "/otp-check";
  static const String otpResend = "/otp-resend";
  static const String getRegions = "/customer/get-areas-by-region";
  static const String home = "/home";
  static const String categoryProducts = "/category-products";
  static const String allCategory = "/all-category";
  static const String prodVariant = "/product-variants";
  static const String addToCart = "/add-to-cart";
  static const String subscriptionCreate = "/subscription-create";
  static const String cartUpdate = "/cart-update";
  static const String romoveCartItem = "/remove-cart-item";
  static const String orderPlace = "/order-place";
  static const String orders = "/orders";
  static const String orderCancel = "/order-cancel";
  static const String mySubscription = "/my-subscription";
  static const String temporaryChange = "/temporary-change";
  static const String pauseSubscription = "/pause-subscription";
  static const String resumeSubscription = "/resume-subscription";
  static const String updateQuantity = "/update-quantity";
  static const String deleteSubscription = "/delete-subscription";
  static const String wallet = "/wallet";
  static const String walletHistory = "/wallet-history";
  static const String billingHistory = "/billing-history";
  static const String paymentRequest = "/payment-request";
  static const String verifyPayment = "/verify-payment";
  static const String payOnline = "/pay-online";
  static const String vacation = "/vacation-update";
  static const String profile = "/profile";
}
